# Generated by Django 4.1.2 on 2022-10-10 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 10, 10, 11, 30, 1, 376577)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
