# Generated by Django 4.1.2 on 2022-10-10 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_created_alter_topic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 10, 10, 11, 43, 55, 878900)),
        ),
    ]
